version: "3.8"

services:
  mongo:
    image: mongo:latest
    command: ["--quiet", "--wiredTigerCacheSizeGB", "0.25"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${KOMODO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DB_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - komodo
    labels:
      komodo.skip: "true"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet --eval 'db.adminCommand({ ping: 1 })' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        # Mongo should generally stay on a single node unless you run a proper replica set.
        max_replicas_per_node: 1

  core:
    image: ghcr.io/moghtech/komodo-core:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    ports:
      - target: 9120
        published: 9120
        protocol: tcp
        mode: ingress
    env_file:
      - ./compose.env
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME: ${KOMODO_DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${KOMODO_DB_PASSWORD}
    volumes:
      - ${COMPOSE_KOMODO_BACKUPS_PATH}:/backups
      # - /path/to/syncs:/syncs
      # - /path/to/core.config.toml:/config/config.toml
    networks:
      - komodo
    labels:
      komodo.skip: "true"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
      placement:
        max_replicas_per_node: 1

  periphery:
    image: ghcr.io/moghtech/komodo-periphery:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    env_file:
      - ./compose.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
    networks:
      - komodo
    labels:
      komodo.skip: "true"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first

networks:
  komodo:
    driver: overlay
    attachable: true

volumes:
  mongo-data:
  mongo-config:
