version: "3.8"

networks:
  traefik-public:
    external: true
  komodo:
    driver: overlay
    attachable: true

services:
  mongo:
    image: mongo:latest
    command: ["--quiet", "--wiredTigerCacheSizeGB", "0.25"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${KOMODO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DB_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - komodo
    labels:
      komodo.skip: "true"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet --eval 'db.adminCommand({ ping: 1 })' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        # Mongo should generally stay on a single node unless you run a proper replica set.
        max_replicas_per_node: 1

  core:
    image: ghcr.io/moghtech/komodo-core:2-dev
    env_file:
      - ./komodo-stack.env
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME: ${KOMODO_DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${KOMODO_DB_PASSWORD}
    #    volumes:
    #      - ${COMPOSE_KOMODO_BACKUPS_PATH}:/backups
    # - /path/to/syncs:/syncs
    # - /path/to/core.config.toml:/config/config.toml
    networks:
      - komodo
      - traefik-public
    labels:
      komodo.skip: "true"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == polaris

      labels:
        - traefik.enable=true

        # HTTP → HTTPS redirect
        - traefik.http.routers.komodo-web.entrypoints=web
        - traefik.http.routers.komodo-web.rule=Host(`komodo.kluhan.dev`)
        - traefik.http.routers.komodo-web.middlewares=redirect-web-to-websecure@internal

        # HTTPS router
        - traefik.http.routers.komodo.entrypoints=websecure
        - traefik.http.routers.komodo.rule=Host(`komodo.kluhan.dev`)
        - traefik.http.routers.komodo.tls=true
        - traefik.http.routers.komodo.tls.certresolver=letsencrypt

        # Backend is plain HTTP on port 9120
        - traefik.http.services.komodo.loadbalancer.server.port=9120

  periphery_polaris:
    image: ghcr.io/moghtech/komodo-periphery:2-dev
    env_file:
      - ./komodo-stack.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
    networks:
      - komodo
    labels:
      komodo.skip: "true"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == polaris
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first

  periphery_vega:
    image: ghcr.io/moghtech/komodo-periphery:2-dev
    env_file:
      - ./komodo-stack.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
    networks:
      - komodo
    labels:
      komodo.skip: "true"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == vega
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first

volumes:
  mongo-data:
  mongo-config:
